name: Danger

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  danger:
    runs-on: macos-latest
    
    env:
      BUNDLE_PATH: vendor/bundle
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      
      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
          
      - name: Set up bundle
        run: |
          gem install bundler:1.17.2 --no-document
          bundle config path ${{ env.BUNDLE_PATH }}
          bundle install --without=documentation --jobs 4 --retry 3
          
      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
