name: PR to main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Validate the head branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          HEAD_BRANCH: ${{ github.head_ref }}
        if: >-
          ${{
            !startsWith(env.HEAD_BRANCH, 'release') &&
            !startsWith(env.HEAD_BRANCH, 'hotfix')
          }}
        run: >
          gh pr comment $PR_URL
          --body '⚠️ You are attempting to merge a branch that is neither release nor hotfix into the main branch.'
